### ISSUE TITLE
运行起来没问题么

### ISSUE THREAD

**Issue by jackeyWanFei** [Saberization/online_signature#1]
![image](https://user-images.githubusercontent.com/20556765/67768591-d5741c80-fa8d-11e9-9577-b13e0c71d04e.png)
是这个样子么

**Comment by jackeyWanFei** [comment]
@Saberization 哈喽哈喽，可以讨论下吗

**Comment by Saberization** [comment]
@jackeyWanFei 由于所在公司的要求，已完成投入业务项目中使用的签章工具版本暂时无法开源，这个仓库中的代码已废弃

**Comment by jackeyWanFei** [comment]
好吧，只能自己解决了
